version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    networks:
      - backend

  node-app:
    build: ./gate-simulator
    ports:
      - "9999:9999"
    networks:
      - backend

networks:
  backend:
    driver: bridge