name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to start
        run: sleep 20

      - name: Run application
        run: java -jar -Dserver.port=8080 ./artifacts/aqa-shop.jar &

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew test --info -Dselenide.headless=true

      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down